#**PRIMERA EVALUACION**
En este documento se desarrolla y analisa un modelo Naive Bayes para fortalecer una herramienta de prevencion de lavado de activos (SARLAFT) en una entidad financiera.
Esto se desarrollara utilizando variables socioeconomicas como:

los Ingresos y Gastos: Transacciones diarias que sirven para deterctar inconsistencias

Monto Transado: Indica la complejidad financiera y la intensidad transacccional

El porcentaje de crecimiento del patrimonio: Detecta
incrementos patrimoniales o cambios bruscos en periodos muy cortos

0.Se cargan las diferentes librerias de trabajo

In [ ]:
import numpy as np #Libreria numerica por excelencia
import pandas as pd #Libreria para la comunicacion con archivos de excel

#Librerias especificas
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix  #permite evaluar los modelos

1.Se cargan los datos de trabajo de la base de datos

In [ ]:
nxl= "/content/sample_data/2. LavadoActivos (1).xlsx"
XDB= pd.read_excel(nxl,sheet_name=0)
XDB.head()
#Seleccionamos las variables de trabajo
XD=XDB[["ingresos_usd","gastos_usd","monto_transado_tarjetas_usd","porcentaje_crecimiento_patrimonio"]] #Variables de trabajo
XD.head(10)
yd=XDB[["lavado_activos"]] #Esta la variable de decision
yd.head()

,lavado_activos
0,1
1,1
2,0
3,0
4,0


2.Implementamos modelo Naive Bayes

In [ ]:
mnb=GaussianNB()
mnb.fit(XD,yd) #Ajustar Variables de entrada-salida

#Mostrar las medias de las variables
u=mnb.theta_
sigma=mnb.var_; sigma= np.sqrt(sigma)
print("ingresos_usd","gastos_usd","monto_transado_tarjetas_usd","porcentaje_crecimiento_patrimonio")
print(u)
print("Las desviaciones son: ")
print(sigma)

ingresos_usd gastos_usd monto_transado_tarjetas_usd porcentaje_crecimiento_patrimonio
[[6.69073255e+03 3.60174970e+03 3.09046404e+03 4.46871435e+01]
 [7.02623043e+04 3.87072844e+04 3.38356197e+04 4.48208630e+01]]
Las desviaciones son: 
[[6.20696435e+03 3.21901567e+03 2.45685863e+03 1.41731672e+01]
 [1.13412265e+05 6.59025571e+04 6.29913911e+04 1.54786058e+01]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**ANALISIS DE RESULTADOS**

De los resultados se observa que los casos clasificados como posible lavado de activos presentan ingresos más altos que los individuos sin riesgo. Sin embargo, estos ingresos no se reflejan en mayores gastos, lo que genera excedentes financieros inusuales y se convierte en una señal de alerta dentro del análisis SARLAFT.

Además, estos individuos muestran mayores montos transados con tarjetas y un crecimiento patrimonial más alto, lo que indica movimientos financieros atípicos y refuerza la importancia de estas variables para identificar perfiles que requieren un análisis más detallado.

3. Se procede con la evaluacion del modelo. Para la evaluacion de este modelo se utiliza una matriz de confusion

In [ ]:
ydp=mnb.predict(XD) #Esto el lo que el modelo aprende - ydp de pronostico
cm=confusion_matrix(yd,ydp)
print(cm)

#se determinan las metricas de la matriz de confusion
VN=cm[0,0]; FP=cm[0,1]; FN=cm[1,0]; VP=cm[1,1]; TDatos=len(XDB)

#1. Exactitud: Funcionamiento general del modelo
Ex=(VP+VN)/TDatos
print("Exactitud: ", Ex)

#2. Tasa de error: porcentaje de fallos del sistema
TE=1-Ex
print("Tasa de error: ", TE)

#3. Sensibilidad: como se comporto el modelo con respecto a los positivos solamente
Se=VP/(VP+FN)
print("Sensibilidad: ", Se)

#4. Especificidad
Es=VN/(VN+FP)
print("Especifisidad: ", Es)

#5. Precision: es una version de como se comporta el modelo frente a los positivos solamente
Pr=VP/(VP+FP)
print("Precision: ", Pr)

#6. Prediccion negativa; Como funciona el modelo pronosticado creditos prenegados
PrN=VN/(VN+FN)
print("Prediccion negativa: ", PrN)


[[2179   44]
 [ 142  785]]
Exactitud:  0.940952380952381
Tasa de error:  0.059047619047619015
Sensibilidad:  0.8468176914778857
Especifisidad:  0.9802069275753487
Precision:  0.9469240048250904
Prediccion negativa:  0.9388194743644981


**ANALISIS DE RESULTADOS**

De acuerdo con los resultados obtenidos, el modelo alcanzó una exactitud superior al 90%, lo que indica un buen comportamiento del modelo frente a la clasificación de los individuos entre posibles casos de lavado de activos y casos sin riesgo. Se destaca la precisión del modelo, la cual fue superior al 94%, lo que evidencia el buen funcionamiento del modelo frente a la identificación de individuos clasificados como riesgo.

Es importante tener en cuenta el buen desempeño del modelo frente a la clasificación de individuos sin riesgo, tal como lo muestra el índice de especificidad, el cual se ubicó por encima del 98%. Esto indica que el modelo clasifica correctamente la mayoría de los individuos que no presentan riesgo de lavado de activos.

Es importante mencionar que la exactitud del modelo se ve afectada por los errores en la clasificación de algunos casos de lavado, lo cual se evidencia a través de la sensibilidad y la predicción negativa, indicando que una parte de los individuos con comportamiento riesgoso no son detectados por el modelo y deben ser evaluados mediante mecanismos de control adicional

4.Evaluar un solicitante para ver como funciona el modelo

In [ ]:
XP=[9000,5000,4000,30]
ydc=mnb.predict([XP])
print(ydc)
XP=[40000,5000,4000,30]
ydc=mnb.predict([XP])
print(ydc)

[0]
[1]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
